### ISSUE TITLE
ADD VALIDATION FOR INPUT DATA FROM STREAM

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/sweatShop-analyze#2]
CHECK FOR REQURIED FIELDS; NO ANALYZE + ERROR IF DATA NOT COMPLETE

**Comment by xlai89** [comment]
Input from stream is validated:
- `msg.Values` must not be empty
- `msg.Values["url"]` must not be empty and must be a valid Url. `git@codehub.example.de/../reponame.git` is not accepted.
- `msg.Values["revision"]` must not be `nil` but can be an empty string `""`
- the repo must be successfully cloned. This checks the auth info and the connection to the repo

**Comment by patrick-hermann-sva** [comment]
perfect
